spring:
  datasource:
    url: jdbc:mysql://localhost:3306/MINTCHOCO
    username: woong
    password: Jhan00254!
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  thymeleaf:
    cache: false
    check-template-location: true
  servlet:
    multipart:
      max-file-size: 5MB # 파일 하나의 최대
      max-request-size: 5MB # 요청의 최대
server:
  port: 8081
  tomcat:
    max-swallow-size: 20MB
file:
  dir: /Users/woong_9yo/Desktop/WorkPlace/mintchoco/upload/
  image:
    ext: .jpg,.jpeg,.svg,.png
    max-size: 5242880
