spring:
  datasource:
    url: jdbc:mysql://localhost:3306/MINTCHOCO
    username: woong
    password: Jhan00254!
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  thymeleaf:
    cache: false
    check-template-location: true
